### PR TITLE
Added method to initialize matched controller from storyboard

### PR DESCRIPTION
**Pull request by roboqo**

### CODE REVIEW

**Comment by skyline75489** [comment]
Hi there! Thanks for the contribution. I'm not really familiar with storyboard. Can you add some test case or example to demonstrate this PR?

**Comment by roboqo** [comment]
Yeah, sure!

**Comment by roboqo** [comment]
Here are some tests to demonstrate how works view controller loading from storyboards. I'm trying to use your amazing routing library in one project, but for me it's much easier to create UI in storyboards.

**Comment by skyline75489** [comment]
The test is good. I'll merge this now. Cheers!

**Pull request merged**
